name: Terraform Apply

# Workflow disabled - uncomment to enable automatic runs on push
# on:
#   push:
#     branches:
#       - dev
#       - stage
#       - main

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TERRAFORM_VERSION: 1.12.0
  ENV_DIR: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_AWS_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_ACCESS_KEY }}
      TF_VAR_AWS_SECRET_KEY: ${{ secrets.TF_VAR_AWS_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./envs/${{ env.ENV_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./envs/${{ env.ENV_DIR }}

      - name: Terraform Output
        run: terraform output -json
        working-directory: ./envs/${{ env.ENV_DIR }}